2025/03/02 20:28:40 get_data.go:99: 连接redis出错，错误信息: dial tcp 127.0.0.1:6379: connect: connection refused
2025/03/02 20:28:40 get_data.go:112: dial tcp 127.0.0.1:6379: connect: connection refused
2025/03/02 20:28:40 get_data.go:122: ============================================================
